http:
  routers:
    nas:
      rule: "Host(`nas.sko`)"
      entryPoints: [web]
      service: nas-service

    photo:
      service: photo-service
      middlewares:
        - "add-photo-prefix"
      rule: "Host(`photo.nas.sko`)"
      entryPoints: [web]

    server:
      rule: "Host(`server.sko`)"
      entryPoints: [web]
      service: server-service

    komodo:
      rule: "Host(`komodo.sko`)"
      entryPoints: [web]
      service: komodo-service

    dozzle:
      rule: "Host(`dozzle.sko`)"
      entryPoints: [web]
      service: dozzle-service

    dnsmasq:
      rule: "Host(`dnsmasq.sko`)"
      entryPoints: [web]
      service: dnsmasq-service

    traefik-dashboard:
      rule: "Host(`traefik.sko`)"
      entryPoints: [web]
      service: traefik-service

  # middlewares:
  #   add-photo-prefix:
  #     addPrefix:
  #       prefix: "/photo"

  services:
    nas-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.101:5000"

    photo-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.101:5000"

    server-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.102"

    komodo-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.102:9120"

    dozzle-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.102:8084"

    dnsmasq-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.102:8080"

    traefik-service:
      loadBalancer:
        servers:
          - url: "http://192.168.88.102:8083"
